add coverage report

diff --git a/.github/workflows/push_pr.yml b/.github/workflows/push_pr.yml
--- a/.github/workflows/push_pr.yml
+++ b/.github/workflows/push_pr.yml
@@ -1,12 +1,15 @@
 name: Run code tests on push and pull requests
 on:
   push:
+    branches:
+      - master
   pull_request:
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
 permissions:
   contents: read
+  pull-requests: write
 
 jobs:
   tests:
@@ -38,14 +41,40 @@ jobs:
             pip install sigpy
           fi
 
-      - name: Run PyTest
+      - name: Install PyTest GitHub Annotation Plugin
+        run: pip install pytest-github-actions-annotate-failures
+
+      - name: Run PyTest and Generate Coverage Report
         run: |
           if [ ${{ matrix.include-sigpy }} == "true" ]; then
-            pytest -m "not slow"
+            pytest -m "not slow" --junitxml=pytest.xml \
+              --cov-report=term-missing:skip-covered --cov=sequences | tee pytest-coverage.txt
           else
-            pytest -m "not slow and not sigpy"
+            pytest -m "not slow and not sigpy" --junitxml=pytest.xml \
+              --cov-report=term-missing:skip-covered --cov=sequences | tee pytest-coverage.txt
           fi
         continue-on-error: ${{ matrix.include-sigpy }}
+
+      - name: Verify PyTest XML Output
+        run: |
+          if [ ! -f pytest.xml ]; then
+            echo "PyTest XML report not found. Please check the previous 'Run PyTest' step for errors."
+            exit 1
+          fi
+
+      - name: Post PyTest Coverage Comment
+        id: coverageComment
+        uses: MishaKav/pytest-coverage-comment@v1.1.53
+        with:
+          pytest-coverage-path: ./pytest-coverage.txt
+          junitxml-path: ./pytest.xml
+
+      - name: Set Pipeline Status Based on Test Results
+        if: steps.coverageComment.outputs.errors != 0 || steps.coverageComment.outputs.failures != 0
+        uses: actions/github-script@v7
+        with:
+          script: |
+            core.setFailed("PyTest workflow failed with ${{ steps.coverageComment.outputs.errors }} errors and ${{ steps.coverageComment.outputs.failures }} failures.")
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
