Fix tests, update workflows, support Python 3.12 tests (#237)
* update action versions in pypi workflow

* simplify and speed-up push_pr / test workflow

* add Python 3.12 to test matrix

* fix syntax in sigpy tests

* extend seq.plot() tests and run them for all test sequences

* add coverage report

diff --git a/.github/workflows/push_pr.yml b/.github/workflows/push_pr.yml
--- a/.github/workflows/push_pr.yml
+++ b/.github/workflows/push_pr.yml
@@ -1,48 +1,83 @@
 name: Run code tests on push and pull requests
 on:
   push:
+    branches:
+      - master
   pull_request:
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
+permissions:
+  contents: read
+  pull-requests: write
+
 jobs:
   tests:
-    name: Code tests (Python ${{ matrix.python-version }}, ${{ matrix.os }})
-    runs-on: ${{ matrix.os }}
+    name: Code tests
+    runs-on: ubuntu-latest
+
     strategy:
+      fail-fast: false
       matrix:
-        os: ["ubuntu-latest"]
-        python-version: ["3.8", "3.9", "3.10", "3.11"]
+        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
+        include-sigpy: [true, false]
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      - name: Cache pip dependencies
+        uses: actions/cache@v3
         with:
-          submodules: true
-          lfs: true
-      - uses: conda-incubator/setup-miniconda@v2
+          path: ~/.cache/pip
+          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
+          restore-keys: |
+            ${{ runner.os }}-pip-
+
+      - name: Install PyPulseq and dependencies
+        run: |
+          pip install --upgrade --upgrade-strategy eager .[test]
+          if [ ${{ matrix.include-sigpy }} == "true" ]; then
+            pip install sigpy
+          fi
+
+      - name: Install PyTest GitHub Annotation Plugin
+        run: pip install pytest-github-actions-annotate-failures
+
+      - name: Run PyTest and Generate Coverage Report
+        run: |
+          if [ ${{ matrix.include-sigpy }} == "true" ]; then
+            pytest -m "not slow" --junitxml=pytest.xml \
+              --cov-report=term-missing:skip-covered --cov=sequences | tee pytest-coverage.txt
+          else
+            pytest -m "not slow and not sigpy" --junitxml=pytest.xml \
+              --cov-report=term-missing:skip-covered --cov=sequences | tee pytest-coverage.txt
+          fi
+        continue-on-error: ${{ matrix.include-sigpy }}
+
+      - name: Verify PyTest XML Output
+        run: |
+          if [ ! -f pytest.xml ]; then
+            echo "PyTest XML report not found. Please check the previous 'Run PyTest' step for errors."
+            exit 1
+          fi
+
+      - name: Post PyTest Coverage Comment
+        id: coverageComment
+        uses: MishaKav/pytest-coverage-comment@v1.1.53
         with:
-          auto-update-conda: true
-          python-version: ${{ matrix.python-version }}
-          activate-environment: test
-          environment-file: .github/requirements.yml
-          auto-activate-base: false
-          channels: conda-forge
-      - shell: bash -l {0}
-        run: |
-          conda info
-          conda list
-      # - name: Lint
-      #   shell: bash -l {0}
-      #   run: |
-      #       python -m flake8 pypulseq
-      - name: Run pytest
-        shell: bash -l {0}
-        run: |
-          pip install .
-          pytest -m "not slow and not sigpy"
-      - name: Run pytest[sigpy]
-        shell: bash -l {0}
-        run: |
-          pip install .[sigpy]
-          pytest -m "not slow"
-        continue-on-error: true
+          pytest-coverage-path: ./pytest-coverage.txt
+          junitxml-path: ./pytest.xml
+
+      - name: Set Pipeline Status Based on Test Results
+        if: steps.coverageComment.outputs.errors != 0 || steps.coverageComment.outputs.failures != 0
+        uses: actions/github-script@v7
+        with:
+          script: |
+            core.setFailed("PyTest workflow failed with ${{ steps.coverageComment.outputs.errors }} errors and ${{ steps.coverageComment.outputs.failures }} failures.")
+
+concurrency:
+  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
+
+  # Cancel in-progress runs when a new workflow with the same group name is triggered
+  cancel-in-progress: true
